# A basic redirect rule
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  command = "cd ../.. && pnpm i && cd examles/todomvc && pnpm run build"
  publish = "examples/todomvc/dist"
  base = "examples/todomvc"

  