name: CI
on:
  - push
  - pull_request
jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 9
      - name: install
        run: pnpm install
      - name: format-check
        run: pnpm run format --check
      - name: lint
        run: pnpm run lint
      - name: build
        run: pnpm run build
      - name: smoke
        run: pnpm run smoke
      - name: test
        run: pnpm run test
      - name: publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # add your signature allowed-signers
          git config --local --add ssh.allowedSignersFile ./allowed_signers
          git config --local --add gpg.allowedSignersFile ./allowed_signers
          echo $GITHUB_REF
          git describe --tags --abbrev=0
          git tag -v $(git describe --tags --abbrev=0)
          node .github/workflows/patch-package.json.mjs "$GITHUB_REF"
          pnpm run publish
